# Generated by Django 3.1.7 on 2021-03-31 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymtracker', '0003_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='current_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='gymtracker.profile'),
        ),
        migrations.AlterField(
            model_name='following',
            name='following_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='gymtracker.profile'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
