# Generated by Django 3.1.7 on 2021-04-03 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymtracker', '0004_auto_20210331_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='exercise_name',
            new_name='name',
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_no', models.IntegerField(default=1)),
                ('reps', models.IntegerField(default=1)),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='gymtracker.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout', to='gymtracker.workout'),
        ),
    ]
