# Generated by Django 3.1.7 on 2021-04-04 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymtracker', '0005_auto_20210403_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='owner',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='workout_owner', to='gymtracker.profile'),
            preserve_default=False,
        ),
    ]
