# Generated by Django 3.1.7 on 2021-04-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtracker', '0008_auto_20210404_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise_Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='set',
            name='set_no',
            field=models.IntegerField(null=True),
        ),
    ]
