# Generated by Django 3.1.7 on 2021-04-14 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymtracker', '0009_auto_20210414_2230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercise_Tutorial',
            new_name='Stored_Exercise',
        ),
    ]
